trigger:
  branches:
    include: [main]

pool:
  name: ado-selfhosted-linux

variables:
  - group: petclinic-kv-secrets
  - name: acrServiceConnection
    value: 'acr-migration-sc'

stages:
  - stage: BuildPython
    jobs:
      - job: Build
        steps:
          - script: |
              python3 --version
              pip3 --version
              cd apps/python-flask
              pip3 install -r requirements.txt
              python3 -m compileall .
            displayName: 'Validate Python app'
          - task: Docker@2
            inputs:
              command: buildAndPush
              containerRegistry: '$(acrServiceConnection)'
              repository: 'python-flask'
              Dockerfile: 'apps/python-flask/Dockerfile'
              tags: |
                $(Build.BuildId)
                $(Build.SourceVersion)
