trigger:
  branches:
    include: [main]

pool:
  name: ado-selfhosted-linux

variables:
  - group: petclinic-kv-secrets
  - name: acrServiceConnection
    value: 'acr-migration-sc'

stages:
  - stage: BuildPython
    jobs:
      - job: Build
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
          - script: |
              cd apps/python-flask
              pip install -r requirements.txt
              python -m compileall .
            displayName: 'Validate Python app'
          - task: Docker@2
            inputs:
              command: buildAndPush
              containerRegistry: '$(acrServiceConnection)'
              repository: 'python-flask'
              Dockerfile: 'apps/python-flask/Dockerfile'
              tags: |
                $(Build.BuildId)
                $(Build.SourceVersion)
